### ISSUE TITLE
Support Gradle Kotlin DSL

### ISSUE THREAD

**Issue by yshrsmz** [yshrsmz/BuildKonfig#13]

**Comment by Kiryushin-Andrey** [comment]
@yshrsmz I guess this issue is about using BuildKonfig from Gradle Kotlin DSL, am I right? I'm currently trying to use BuildKonfig from a Gradle Kotlin build script and I have troubles with it (the plugin can't be found when I specify it in plugins section). Is there any workaround for this? Or maybe can you give me any advice on how to contribute to your repo to make it possible - I'd like to give it a try.

**Comment by yshrsmz** [comment]
https://github.com/yshrsmz/BuildKonfig/issues/15#issuecomment-553102921

Please refer to this comment for the current usage in kts files.

Regarding your contribution, please feel free to send a PR like any other oss repositories, but let's discuss API interface first.

**Comment by Kiryushin-Andrey** [comment]
Thanks, that helped a lot! However, I also had another issue that isn't described in this comment. I wasn't able to use the plugin just by adding `id("com.codingfeline.buildkonfig") version "0.5.1"` to the plugins section of my `build.grade.kts` file, because Gradle couldn't locate the plugin with specified id.

I found a workaround after looking into Gradle docs for a while (https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_resolution_rules). I added a resolution strategy to the pluginManagement block of the `settings.gradle.kts` file:
```
pluginManagement {
    repositories {
        center()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "com.codingfeline.buildkonfig") {
                useModule("com.codingfeline.buildkonfig:buildkonfig-gradle-plugin:${requested.version}")
            }
        }
    }
```
From what I've read in https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers and https://docs.gradle.org/current/userguide/java_gradle_plugin.html it looks like plugin marker artifacts aren't being published to any of the central repositories. I'm new to Gradle and I may be wrong, but this is what I suggest to fix so that no resolutionStrategy is needed on the consumer side.

**Comment by yshrsmz** [comment]
Thanks, yeah I need to check the maven/release configurations and create a new release.

**Comment by yshrsmz** [comment]
@Kiryushin-Andrey 

Hi, it's a bit late but the plugin is now on Gradle Plugins Portal.
If you are still interested in, please try it out.

https://plugins.gradle.org/plugin/com.codingfeline.buildkonfig

**Comment by Coronel-B** [comment]
> @Kiryushin-Andrey
> 
> Hi, it's a bit late but the plugin is now on Gradle Plugins Portal.
> If you are still interested in, please try it out.
> 
> https://plugins.gradle.org/plugin/com.codingfeline.buildkonfig

Great, this works!
